name: Firebase Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
      - name: Deploy to Firebase
        working-directory: frontend-admin # specify the root directory for the deployment
        run: |
          firebase deploy --only hosting # deploy only the hosting portion
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_ADMIN }} # set up the Firebase token secret for authentication
